set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLE x86_64-w64-mingw32 CACHE STRING "MinGW-w64 target triple")

set(CMAKE_C_COMPILER ${MINGW_TRIPLE}-gcc CACHE FILEPATH "MinGW-w64 C compiler")
set(CMAKE_CXX_COMPILER ${MINGW_TRIPLE}-g++ CACHE FILEPATH "MinGW-w64 C++ compiler")
set(CMAKE_RC_COMPILER ${MINGW_TRIPLE}-windres CACHE FILEPATH "MinGW-w64 resource compiler")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
